server:
  servlet:
    context-path: /
  port: 8889



spring:
  application:
    name: web-server-01
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
thymeleaf:
  prefix: classpath:/templates/
  cache: false



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:32514/eureka/ #eureka注册地址



#配置验证码
FontSize: 18
width: 100
height: 30
lineSize: 50
CodeNum: 4
CodeKey: CateyeKey


